name: deploy2nekoweb

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

        # your build step here

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v1.0.0
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: '/'
          directory: 'nekoweb'
